<?php

namespace Sequode\Application\Modules\Session;

use Sequode\Model\Database\SQL\ORM;

class Model extends ORM {

    const Database_Connection     =   'sessions_database';

    const Table                   =	'sessions';

    const Normalizations = [
        'session_data' =>
            [
                'get' => 'serializedToObject',
                'set' => 'objectToSerialized'
            ]
    ];

    public function exists($value, $by = 'session_id')
    {
        return parent::exists($value, $by); // TODO: Change the autogenerated stub
    }
}